title: "Nanda's TIL"
description: "Things I learned, one day at a time"
url: ""
baseurl: "/nanda-today-i-learned"
permalink: /:year/:month/:day/:title/
markdown: kramdown

theme: null

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitkeep
